events {
    # Define la cantidad máxima de conexiones simultáneas por worker
    worker_connections 1024;
}

http {
    # 1. Redirección de HTTP a HTTPS
    server {
        listen 80;
        server_name sso.local localhost;

        # Cualquier petición al puerto 80 es redirigida al 443 conservando la ruta
        return 301 https://$host$request_uri;
    }

    # 2. Servidor Principal HTTPS
    server {
        listen 443 ssl;
        server_name sso.local localhost;

        # Rutas de los certificados SSL (estas rutas existirán dentro del contenedor)
        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

        # Configuraciones de seguridad SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # ----------------------------------------------------
        # Backend: NestJS (SSO API)
        # ----------------------------------------------------
        # Intercepta cualquier petición que empiece con /api/
        location /api/ {
            # Apunta al nombre del servicio Docker (sso-api) y su puerto interno (3001)
            proxy_pass http://sso-api:3001;

            # Traspaso de cabeceras originales
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Cabecera crítica para que NestJS reconozca el contexto seguro
            # y permita configurar las cookies con Secure=true
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ----------------------------------------------------
        # Frontend: Angular (SSO Web)
        # ----------------------------------------------------
        # Intercepta el resto del tráfico (la raíz y rutas de la interfaz)
        location / {
            # Ahora apuntamos al puerto 80 del contenedor estático
            proxy_pass http://sso-web:80;

            # Traspaso de cabeceras
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}